[project]
name = "ai-animal-classifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.3.3",
    "scipy>=1.15.3",
    "streamlit>=1.52.1",
    "tensorflow>=2.20.0",
]
